import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        
        <h1 className={styles.title}>
          Welcome to <a href="https://kubernetes.io/">K8 learning session!</a>
        </h1>
        <br />
        <br />
        <h4 className={styles.subTitle}>
        Power of K8 is the ability to scale and manage your application without any downtime.
        </h4>
        <br />
        <br/>
        <Image src='/k8.png' alt='k8' height={250} width={650} />
        

        
      </main>

     
    </div>
  )
}
